### ISSUE TITLE
Adding nucleotide/AA letter to the alignment

### ISSUE THREAD

**Issue by michaelniklaus** [sjspielman/alignfigR#2]
Is there a neat way to include the sequence characters in the alignment instead of having it in the figure legend? Following your example in "Introduction to alignfiR":
`p1 <- plot_alignment(my_data, "DNA")`
`p1`  
plotting the sequence characters as well:
`p1 + geom_text(size=15)`

Thank you!

**Comment by sjspielman** [comment]
Hi @michaelniklaus, 

Currently there is no specific feature to accomplish this, but I do plan on adding it in the relatively near future. Stay tuned for updates!

Best, 
Stephanie
